spring:
  # Session management

  security:
    oauth2:
      client:
        registration:
          azure:
            client-id: 215b5640-18a9-4579-85f0-dee13df57b61
            client-secret: txu8Q~zcxhqoui7SJI~1QMkOF3cgvTMSw584IajE
            scope:
              - openid
              - profile
              - email
              - https://graph.microsoft.com/User.Read
              - https://graph.microsoft.com/User.ReadBasic.All
            redirect-uri: http://localhost:8080/ssoapi/login/oauth2/code/
            client-name: Azure AD
        provider:
          azure:
            authorization-uri: https://login.microsoftonline.com/3dbd7e58-e2ea-40b8-bb5a-3ea2038c9535/oauth2/v2.0/authorize
            token-uri: https://login.microsoftonline.com/3dbd7e58-e2ea-40b8-bb5a-3ea2038c9535/oauth2/v2.0/token
            user-info-uri: https://graph.microsoft.com/oidc/userinfo
            jwk-set-uri: https://login.microsoftonline.com/3dbd7e58-e2ea-40b8-bb5a-3ea2038c9535/discovery/v2.0/keys
            user-name-attribute: sub
            issuer-uri: https://login.microsoftonline.com/3dbd7e58-e2ea-40b8-bb5a-3ea2038c9535/v2.0



  jwt:
    secret: ${JWT_SECRET}
  mail:
    host: smtp.gmail.com
    port: 587
    username: noreply.clarium.sso@gmail.com
    password: tswdzlzgfwyaqank
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# Server configuration
server:
  forward-headers-strategy: framework
  servlet:
    context-path: /ssoapi
    session:
      timeout: 30m
      tracking-modes: cookie
      cookie:
        name: JSESSIONID
        http-only: true
        secure: false
        max-age: 1800
        same-site: lax

# Logging for debugging
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    com.clarium.clarium_sso.service.LogoutService: DEBUG

app:
  blocked-url: "http://localhost:8080"

environmenturl:
  successurl: "http://localhost:4200/overview"
  failureurl: "http://localhost:4200/login"

